name: Jest Tests

on:
  pull_request:
    branches:
      - master

env:
  TEST_DATABASE_NAME: test_db
  DATABASE_USERNAME: root
  DATABASE_PASSWORD:
  DATABASE_HOST: localhost
  DATABASE_DIALECT: mysql
  S3_REGION: ${{ secrets.REGION }}
  S3_BUCKET_PATH: ${{ secrets.S3BUCKETPATH }}
  S3_BUCKET: ${{ secrets.BUCKETNAME }}
  S3_ACCESS_KEY_ID: ${{ secrets.ACCESSKEYID }}
  S3_SECRET_ACCESS_KEY: ${{ secrets.SECRETACCESSKEY }}
  SECRET: ${{ secrets.SECRET }}
jobs:
  jest_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Set up MySql
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
      
      - name: Create test-db
        run: mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS test_db'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Jest tests
        run: npm run test
